version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
#      - static-volume:/data/static
#      - media-volume:/data/media
    ports:
      - 80:80
  django_container_gunicorn:
    image: django_test_image:5
    networks:
      - network
    secrets:
      - DJANGO_SECRET_KEY
      - MYSQL_ROOT_PASSWORD
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - maria-database:/var/lib/mysql
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD

networks:
  network:

volumes:
  maria-database:

secrets:
   EMAIL_HOST_USER:
     external: true
   EMAIL_HOST_PASSWORD:
     external: true
   MYSQL_ROOT_PASSWORD:
     external: true
   MYSQL_PASSWORD:
     external: true
   DJANGO_SECRET_KEY:
     external: true
